version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
    # Ignore updates to 'webpack' ^5.0 as this is not compatible with 'parallel-webpack'
    - dependency-name: "webpack"
      versions: ["5.x"]
