name: 'Bump Version Plus'

on:
  push:
    branches:
      - 'main'

jobs:
  bump-version:
    name: 'Bump version on main'
    runs-on: ubuntu-latest
    if: ${{ ! contains(github.issue.comment.body, 'dependabot') }}

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}
      - name: Automated Version Bump Plus
        uses: 'mhillerstrom/gh-action-bump-version-plus@v2.0.4'
        id: version-bump
        with:
          tag-prefix: 'v'
          skip-if-commit-contains: 'Dependabot'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'cat package.json'
        run: cat ./package.json
      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
